/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.sadko.gestures;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int Button01=0x7f050017;
        public static final int EditText01=0x7f050002;
        public static final int LinearLayout01=0x7f050000;
        public static final int LinearLayout02=0x7f050006;
        public static final int LinearLayout03=0x7f05000c;
        public static final int ListView01=0x7f05000d;
        public static final int RadioButton01=0x7f050011;
        public static final int Record=0x7f050003;
        public static final int RelativeLayout01=0x7f05000e;
        public static final int TextView01=0x7f050001;
        public static final int activities=0x7f050013;
        public static final int add_new=0x7f050007;
        public static final int app_name=0x7f050016;
        public static final int apps=0x7f050012;
        public static final int delete=0x7f050008;
        public static final int exit=0x7f05000a;
        public static final int modify=0x7f050009;
        public static final int name=0x7f05000f;
        public static final int no=0x7f050015;
        public static final int okay=0x7f050014;
        public static final int path=0x7f050010;
        public static final int pick=0x7f050004;
        public static final int sSandE=0x7f050005;
        public static final int service_start=0x7f05000b;
    }
    public static final class layout {
        public static final int edit=0x7f030000;
        public static final int main=0x7f030001;
        public static final int motions_row=0x7f030002;
        public static final int picker=0x7f030003;
        public static final int picker_item=0x7f030004;
        public static final int record=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
